#!/bin/bash

set -x

set -eo pipefail

# When the custom image is run as a S2I builder we allow for the user to
# provide their own plugins, themes and languages directories. We need to
# stash these away and they will be applied only when the final application
# image is run so that they can be applied to what is contained in the
# persistent volume.

mkdir -p /opt/app-root/downloads

mkdir -p /tmp/src/system
mkdir -p /tmp/src/image
mkdir -p /tmp/src/download
mkdir -p /tmp/src/extensions
mkdir -p /tmp/src/resources

mv /tmp/src/system /opt/app-root/downloads/system
mv /tmp/src/image /opt/app-root/downloads/image
mv /tmp/src/download /opt/app-root/downloads/download
mv /tmp/src/extensions /opt/app-root/downloads/extensions
mv /tmp/src/resources /opt/app-root/downloads/resources


rm -rf /tmp/src
