#!/bin/bash

set -x

set -eo pipefail

ls /opt/app-root/src/


if [[ -f "system/config.php" ]]; then
    
    # if it is already installer, copy all the source code except images, cache, logs...
    cp -Rf /opt/app-root/downloads/admin/* /opt/app-root/src/admin/
    cp -Rf /opt/app-root/downloads/extensions/* /opt/app-root/src/extensions/
    cp -Rf /opt/app-root/downloads/storefront/* /opt/app-root/src/storefront/
    cp -Rf /opt/app-root/downloads/core/* /opt/app-root/src/core/
    cp -Rf /opt/app-root/downloads/static_pages/* /opt/app-root/src/static_pages/

else
    
    # if abantecart is not installed yet
    # copy all the source code
    cp -Rf /opt/app-root/downloads/* /opt/app-root/src/
    
    # execute the installer
    php install/cli_install.php install \
        --db_host=$MYSQL_HOST \
        --db_user=$MYSQL_USER \
        --db_password=$MYSQL_PASSWORD \
        --db_name=$MYSQL_DATABASE \
        --db_driver=apdomysql \
        --db_prefix=abc \
        --admin_path=admin \
        --username=admin \
        --password=admin \
        --email=mail@mail.com \
        --http_server=http://localhost
fi

exec /usr/libexec/s2i/run
