#!/bin/bash

set -x

set -eo pipefail

if grep -q "SERVER_NAME" system/config.php; [ $? -eq 0 ]; then    

    php install/cli_install.php install 
        --db_hostname=$MYSQL_HOST
        --db_username=$MYSQL_USER
        --db_password=$MYSQL_PASSWORD
        --db_database=$MYSQL_DATABASE
        --db_driver=mysqli
        --db_port=3306
        --username=admin
        --password=AiT1448
        --email=billy@baldisser.com
        --http_server=http://localhost

fi


# if [ -f /opt/app-root/downloads/system ]; then
#     cp -f /opt/app-root/downloads/system/* system
# fi

if [ -f /opt/app-root/downloads/image ]; then
    cp -f /opt/app-root/downloads/image/* image
fi

if [ -f /opt/app-root/downloads/download ]; then
    cp -f /opt/app-root/downloads/download/* download
fi

# if [ -f /opt/app-root/downloads/extensions ]; then
#     cp -f /opt/app-root/downloads/extensions/* extensions
# fi

if [ -f /opt/app-root/downloads/resources ]; then
    cp -f /opt/app-root/downloads/resources/* resources
fi


exec /usr/libexec/s2i/run
